-- Superbase SQL Schema for Smart Home Grocery Management System

-- Enable UUIDs (standard practice, though we use BIGINT for IDs per request)
create extension if not exists "uuid-ossp";

-- 1. ITEMS
create table public.items (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text,
  category text,
  alt_brand text,
  min_threshold integer default 5
);

-- 2. STORAGE_LOCATION
create table public.storage_location (
  id bigint generated by default as identity primary key,
  location_name text not null,
  temp integer, -- Celsius
  height integer, -- cm
  width integer, -- cm
  depth integer -- cm
);

-- 3. ITEM_STOCK
create table public.item_stock (
  id bigint generated by default as identity primary key,
  item_id bigint references public.items(id) on delete cascade not null,
  storage_id bigint references public.storage_location(id) on delete set null,
  days_left integer, -- Recommended to calculate dynamically in frontend: (expiry_date - current_date)
  expiry_date date not null,
  current_qty integer default 0 check (current_qty >= 0)
);

-- 4. PERSON
create table public.person (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text,
  location text,
  age integer,
  phone_no text
);

-- 5. USAGE_LOG
create table public.usage_log (
  log_id bigint generated by default as identity primary key,
  item_id bigint references public.items(id) on delete cascade not null,
  person_id bigint references public.person(id) on delete set null,
  used_date date default current_date,
  used_qty integer not null check (used_qty > 0)
);

-- 6. RECIPES
create table public.recipes (
  id bigint generated by default as identity primary key,
  name text not null,
  difficulty text,
  prep_time integer,
  ingredients jsonb -- e.g. [{"item_id": 1, "qty": 2}]
);

-- 7. SHOPPING_LIST
create table public.shopping_list (
  id bigint generated by default as identity primary key,
  item_id bigint references public.items(id) on delete cascade not null,
  status text check (status in ('pending', 'purchased')) default 'pending',
  added_date date default current_date
);

-- ==========================================
-- TRIGGERS & FUNCTIONS
-- ==========================================

-- Function to decrement stock on usage log insert (FIFO)
create or replace function decrement_stock_on_usage() returns trigger as $$
declare
  remaining_qty integer := new.used_qty;
  stock_rec record;
begin
  -- Iterate through stock ordered by expiry (oldest first)
  for stock_rec in 
    select * from public.item_stock 
    where item_id = new.item_id and current_qty > 0
    order by expiry_date asc
  loop
    if remaining_qty <= 0 then
      exit;
    end if;

    if stock_rec.current_qty >= remaining_qty then
      -- Current batch satisfies remaining demand
      update public.item_stock 
      set current_qty = current_qty - remaining_qty
      where id = stock_rec.id;
      remaining_qty := 0;
    else
      -- Consume entire batch and continue
      remaining_qty := remaining_qty - stock_rec.current_qty;
      update public.item_stock 
      set current_qty = 0
      where id = stock_rec.id;
    end if;
  end loop;
  
  return new;
end;
$$ language plpgsql;

create trigger on_usage_log_insert
after insert on public.usage_log
for each row execute function decrement_stock_on_usage();

-- Function to check low stock and add to shopping list
create or replace function check_stock_threshold() returns trigger as $$
declare
  target_item_id bigint;
  total_qty integer;
  threshold integer;
  item_exists boolean;
begin
  if (TG_OP = 'DELETE') then
    target_item_id := old.item_id;
  else
    target_item_id := new.item_id;
  end if;
  
  -- Calculate total current stock
  select coalesce(sum(current_qty), 0) into total_qty
  from public.item_stock
  where item_id = target_item_id;
  
  -- Get threshold
  select min_threshold into threshold
  from public.items
  where id = target_item_id;
  
  -- If stock is low, verify if already in pending list
  if total_qty < threshold then
    select exists(
      select 1 from public.shopping_list 
      where item_id = target_item_id and status = 'pending'
    ) into item_exists;
    
    if not item_exists then
      insert into public.shopping_list (item_id, status, added_date)
      values (target_item_id, 'pending', current_date);
    end if;
  end if;
  
  return null; -- After trigger doesn't need return value
end;
$$ language plpgsql;

create trigger on_stock_update
after update or insert or delete on public.item_stock
for each row execute function check_stock_threshold();

-- ==========================================
-- RLS POLICIES (Public Access for MVP)
-- ==========================================
-- In a real app, you'd restrict write access to authenticated users.

alter table items enable row level security;
alter table item_stock enable row level security;
alter table storage_location enable row level security;
alter table person enable row level security;
alter table usage_log enable row level security;
alter table recipes enable row level security;
alter table shopping_list enable row level security;

-- Allow public read/write
create policy "Public Access Items" on items for all using (true) with check (true);
create policy "Public Access Stock" on item_stock for all using (true) with check (true);
create policy "Public Access Location" on storage_location for all using (true) with check (true);
create policy "Public Access Person" on person for all using (true) with check (true);
create policy "Public Access Log" on usage_log for all using (true) with check (true);
create policy "Public Access Recipes" on recipes for all using (true) with check (true);
create policy "Public Access List" on shopping_list for all using (true) with check (true);
